version: '3.5'

networks:
  default:
    name: tdm_default
services:
  masking:
    image: tdm/masking:4.9.38.0
    environment:
      - 'MESSAGING_SERVER=messaging'
      - 'MESSAGING_PORT=5671'
      # Specify your messaging credentials here
      # These values should match the credentials which have been specified
      # in the tdmweb container above. These are the user credentials
      # that the masking service will use to connect to the message broker.
      - 'MESSAGING_USER=Admin'
      - 'MESSAGING_PASS={cry}1hY5pZrm87PWjgPdmypDbVZnL4a108lxy8YLuUVRMCr8'
    depends_on:
      - messaging
    volumes:
      - 'masking_storage:/mnt/storage'
      - 'masking_logs:/mnt/logs'
      - 'masking_seedtables:/mnt/seedtablesCustom'
volumes:
  masking_logs:
  masking_storage:
  masking_seedtables:
